# Generated by Django 6.0.7 on 2026-07-21 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('location', models.CharField(blank=True, default='', max_length=100)),
                ('preferred_role', models.CharField(blank=True, default='', max_length=100)),
                ('experience', models.CharField(blank=True, default='', max_length=50)),
                ('expected_salary', models.CharField(blank=True, default='', max_length=50)),
                ('preferred_location', models.CharField(blank=True, default='', max_length=100)),
                ('skills', models.TextField(blank=True, default='React, Node.js, Django, Python')),
                ('github', models.CharField(blank=True, default='', max_length=200)),
                ('linkedin', models.CharField(blank=True, default='', max_length=200)),
                ('portfolio', models.CharField(blank=True, default='', max_length=200)),
                ('leetcode', models.CharField(blank=True, default='', max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
